### ISSUE TITLE
How I can Validate My HL7 Message

### ISSUE THREAD

**Issue by shirajmomin** [nHapiNET/nHapi#60] opened 2016-09-14 09:15 UTC
Hello,

I am using nHapi, but when I validate my HL7 message its give always success message.

even I have updated with wrong value still its give success message.

**Comment by milkshakeuk** [comment] 2022-01-09 10:36
@shirajmomin i believe this is a duplicate of #46

**Closed** 2022-01-09 10:53 UTC
Labels: duplicate

**Comment by milkshakeuk** [comment] 2022-02-02 09:02
@shirajmomin also there are some useful tutorials on validating with nhapi [here](https://saravanansubramanian.com/hl7tutorials/#hl7-programming-tutorials-using-nhapi-and-net).
